[WIP] Cypress tests for FormContextWithValidation
iusehooks/usetheform pull request #47
Opened 2024-04-07 04:00 UTC by AshwinNema

Hi @iusehooks,

I am still working but here is my first PR for https://github.com/iusehooks/usetheform/issues/24. Please let me know if anything has to be changed

2024-04-07 09:12 UTC, iusehooks commented
Hi, It looks good so far. 

We should add into `.gitignore`  a new path for excluding `cypress/videos`

Well done. 

Thanks

2024-04-15 14:54 UTC, AshwinNema commented
Hi @iusehooks,

I have added all the tests. Please let me know if any changes have to be made

2024-04-25 09:29 UTC, iusehooks requested changes

2024-04-25 14:13 UTC, AshwinNema commented on package.json
> -    "dev": "rimraf dev coverage && concurrently \"node ./build_config/dev.js\" \"browser-sync start --server examples --ss dev --files dev --files examples\""
@iusehooks  I have added cypress folder in the lint command script and I have fixed the issues after running lint command

2024-05-05 08:32 UTC, iusehooks approved these changes

2024-05-05 08:32 UTC, merged